### ISSUE TITLE
DPdash deployment error

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#282]
```js
Apptainer> singularity/run.sh
Starting superivsord...
Starting dpdash...

> po@0.0.0 transpile
> npx babel ./server --out-dir dist

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
SyntaxError: /sw/apps/dpdash/server/configs/config.js: Unexpected token, expected "," (2:57)

  1 | import path from 'path';
> 2 | const cert = path.normalize(("/data/ssl/client/cert.pem");
    |                                                          ^
  3 | const key = path.normalize(("/data/ssl/client/key.pem");
  4 | const ca = path.normalize(("/data/ssl/ca/cacert.pem");
  5 |
    at instantiate (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:367:12)
    at Parser.raise (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:3706:19)
    at Parser.unexpected (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:3744:16)
    at Parser.expect (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:4157:28)
    at Parser.parseCallExpressionArguments (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:13050:14)
    at Parser.parseCoverCallAndAsyncArrowHead (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:12965:29)
    at Parser.parseSubscript (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:12890:19)
    at Parser.parseSubscripts (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:12859:19)
    at Parser.parseExprSubscripts (/sw/apps/dpdash/node_modules/@babel/parser/lib/index.js:12848:17) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 2, column: 57, index: 82 },
  pos: [Getter/Setter]
}

```

**Comment by tashrifbillah** [comment]
Coming from:
https://github.com/AMP-SCZ/dpdash/blob/7289af07bc8ef4b6452abfd008d2e10519440b3f/singularity/run.sh#L38

**Comment by tashrifbillah** [comment]
Missing `)` in these lines:
https://github.com/AMP-SCZ/dpdash/blob/7289af07bc8ef4b6452abfd008d2e10519440b3f/singularity/configure.py#L312-L314
