### ISSUE TITLE
init.sh error: read-only file system, open 'dist/app.js'

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#39]
https://github.com/AMP-SCZ/dpdash/blob/2d995e92a2af8f694dedc15da3e1f8c56424abba/singularity/setup.sh#L41

Reports the following error during `./init.sh`:

```bash
webpack 5.36.1 compiled with 4 warnings in 421575 ms

> po@0.0.0 transpile
> npx babel ./server --out-dir dist

Error: EROFS: read-only file system, open 'dist/app.js'
    at Object.openSync (node:fs:506:3)
    at Object.writeFileSync (node:fs:1552:35)
    at outputFileSync (/sw/apps/dpdash/node_modules/@babel/cli/lib/babel/dir.js:35:6)
    at /sw/apps/dpdash/node_modules/@babel/cli/lib/babel/dir.js:77:11
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/sw/apps/dpdash/node_modules/@babel/cli/lib/babel/dir.js:14:103)
    at _next (/sw/apps/dpdash/node_modules/@babel/cli/lib/babel/dir.js:16:194) {
  errno: -30,
  syscall: 'open',
  code: 'EROFS',
  path: 'dist/app.js'
}
```

**Comment by tashrifbillah** [comment]
This issue probably had happened with an outdated Singularity image.

Marked for closing
