### ISSUE TITLE
npm start before mongod initialization causes TypeError: undefined collection

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#407]
Error on front end upon login at https://predict.bwh.harvard.edu/dpdash/:

> TypeError: Cannot read properties of undefined (reading 'collection'

Errors on `~/.pm2/logs/www-error.log`:
```
TypeError: Cannot read properties of undefined (reading 'collection')
    at Strategy._verify (/sw/apps/dpdash/dist/app.js:212:11)
    at Strategy.authenticate (/sw/apps/dpdash/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/sw/apps/dpdash/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/sw/apps/dpdash/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at /sw/apps/dpdash/dist/routes/index.js:243:5
    at Layer.handle [as handle_request] (/sw/apps/dpdash/node_modules/express/lib/router/layer.js:95:5)
    at next (/sw/apps/dpdash/node_modules/express/lib/router/route.js:137:13)
    at next (/sw/apps/dpdash/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/sw/apps/dpdash/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/sw/apps/dpdash/node_modules/express/lib/router/layer.js:95:5)
    at /sw/apps/dpdash/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/sw/apps/dpdash/node_modules/express/lib/router/index.js:335:12)
    at next (/sw/apps/dpdash/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/sw/apps/dpdash/node_modules/express/lib/router/index.js:174:3)
    at router (/sw/apps/dpdash/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/sw/apps/dpdash/node_modules/express/lib/router/layer.js:95:5)
```

---

Tashrif diagnosed that this error is causes by insufficient delay between mongod server start and `npm start`:
https://github.com/AMP-SCZ/dpdash/blob/e80d1951d9a4138689db10926650be2b483d9a25/singularity/run.sh#L31-L39

The mishap can also be attributed to mongod taking longer to initialize. Here is the detailed reason:

This MongoDB constructor appears to run only once when the app starts:
https://github.com/AMP-SCZ/dpdash/blob/3e7e0b0d3dbe358bedfa5c5737a1daee165851b3/server/app.js#L105-L119

My diagnosis is that mongod server starts a few moment after the above block aims to generate that constructor. As a result, `node.js` cannot find that constructor and reports that collection as undefined. I think this is the error that prevents rest of the JavaScript code execution even when mongod has come live. As a result, we could never log in from the front end.

**Comment by tashrifbillah** [comment]
#### Solution

Tashrif discovered that when `mongod` is running, if `npm restart` is run, the server comes back online. Tashrif also inserted a `console.log()` before `dpdash/server/app.js:106` to realize that the constructor runs only once and not everything a user tries to log in. So the naive solution is to wait for more than 100 seconds before `npm start`.

**Comment by tashrifbillah** [comment]
However, there may be an intelligent solution:

(The following change is locally present in rc-predict. It will be committed if successful after next OS patching.)

```bash
 # clear previous logs
 rm -f ~/.pm2/logs/*
-rm -f /data/dpdash/mongodb/logs/mongod.log
+rm -f `find /data/dpdash/ -type f -name "*log"`
 rm -f /data/dpdash/mongodb/dbs/diagnostic.data/*
 
 # start mongodb, celery, and rabbit
@@ -30,6 +30,11 @@ echo "Starting superivsord..."
 supervisord -c /data/dpdash/configs/supervisord.conf
 
 # sleep 100 seconds
+# mongod is the one that takes most time to start and causes
+# https://github.com/AMP-SCZ/dpdash/issues/407
+# so let's wait for mongod to start
+while [ -z `pgrep -f mongod` ]; do sleep 30; done
+# sleep more for safeguard
 sleep 100

```

![image](https://github.com/AMP-SCZ/dpdash/assets/35086881/4e8b7664-d3e7-486d-9eff-45d651af7a64)

Tashrif will test it next time predict-DPdash goes down.

**Comment by tashrifbillah** [comment]
A few Google sources such as https://stackoverflow.com/questions/61008735 recommended changing localhost to 127.0.0.1 but that was not our issue.
