### ISSUE TITLE
Occasional MongoError: pool destroyed

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpdash#41]
* It happens sporadically
* The web application crashes when it happens
* It was also observed to happen after first import of data to a new DPdash web application
* It was also observed to happen when a new user signed up

```bash
[tb571@rc-predict-dev ~] cd /home/tb571/.pm2/logs
[tb571@rc-predict-dev logs]$ tail -f -n 0 www-error.log
```

<details><summary>www-error.log</summary>

```bash
(Use `node --trace-warnings ...` to show where the warning was created)
MongoError: ns not found
    at Connection.<anonymous> (/sw/apps/dpdash/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (node:events:394:28)
    at processMessage (/sw/apps/dpdash/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at TLSSocket.<anonymous> (/sw/apps/dpdash/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at TLSSocket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:226:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 26,
  codeName: 'NamespaceNotFound'
}
MongoError: pool destroyed
    at Pool.write (/sw/apps/dpdash/node_modules/mongodb/lib/core/connection/pool.js:841:8)
    at _command (/sw/apps/dpdash/node_modules/mongodb/lib/core/wireprotocol/command.js:120:10)
    at command (/sw/apps/dpdash/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
    at Object.query (/sw/apps/dpdash/node_modules/mongodb/lib/core/wireprotocol/query.js:66:3)
    at Server.query (/sw/apps/dpdash/node_modules/mongodb/lib/core/topologies/server.js:644:16)
    at FindOperation.execute (/sw/apps/dpdash/node_modules/mongodb/lib/operations/find.js:38:12)
    at /sw/apps/dpdash/node_modules/mongodb/lib/operations/execute_operation.js:144:17
    at Server.selectServer (/sw/apps/dpdash/node_modules/mongodb/lib/core/topologies/server.js:832:3)
    at Server.selectServer (/sw/apps/dpdash/node_modules/mongodb/lib/topologies/topology_base.js:342:32)
    at executeWithServerSelection (/sw/apps/dpdash/node_modules/mongodb/lib/operations/execute_operation.js:131:12)
    at /sw/apps/dpdash/node_modules/mongodb/lib/operations/execute_operation.js:70:9
    at maybePromise (/sw/apps/dpdash/node_modules/mongodb/lib/utils.js:685:3)
    at executeOperation (/sw/apps/dpdash/node_modules/mongodb/lib/operations/execute_operation.js:34:10)
    at Cursor._initializeCursor (/sw/apps/dpdash/node_modules/mongodb/lib/core/cursor.js:534:7)
    at Cursor._initializeCursor (/sw/apps/dpdash/node_modules/mongodb/lib/cursor.js:186:11)
    at nextFunction (/sw/apps/dpdash/node_modules/mongodb/lib/core/cursor.js:737:10)
```

</details>

```bash
[tb571@rc-predict-dev ~] cd /home/tb571/.pm2/logs
[tb571@rc-predict-dev logs]$ tail -f -n 0 www-out.log
```

<details><summary>www-out.log</summary>

```bash
{"message":"127.0.0.1 - unidentified [19/Dec/2021:05:17:11 +0000] \"GET /dpdash/img/dpdash.png HTTP/1.1\" 200 32498 \"http://localhost:8001/dpdash/login\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62\"\n","level":"info"}
stderr: node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module '/sw/apps/dpdash/utils/importer.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

child process exited with code 1
{"message":"127.0.0.1 - unidentified [19/Dec/2021:15:38:52 +0000] \"GET /dpdash HTTP/1.1\" 302 72 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62\"\n","level":"info"}
```

</details>

The apparent solution is to [quit.sh](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/README-PNL.md#quit) and [run.sh](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/README-PNL.md#run)--which is essentially restarting the system upon every crash.

**Comment by tashrifbillah** [comment]
We have killed the other instance but observed the same issue. Hence, the title has been updated.

**Comment by tashrifbillah** [comment]
Not sure if the above issue showed all zeros in the `admin` home page but I am able to see projects upon [setting up access](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/README-PNL.md#set-up-access).

**Comment by tashrifbillah** [comment]
This issue happens on login attempt at the first instantiation of DPdash. I [quit.sh](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/README-PNL.md#quit) and [run.sh](https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/README-PNL.md#run). Now login is successful in the second instantiation of DPdash.

**Comment by tashrifbillah** [comment]
According to https://stackoverflow.com/a/39168601/11932012, connections are closed too soon yielding the error. The following places are being looked at to find issues:

```vim
server/routes/index.js:2:import { MongoClient, ObjectID } from 'mongodb';
server/routes/index.js:50:MongoClient.connect(mongoURI, config.database.mongo.server, function (err, client) {
server/routes/index.js:63:    MongoClient.connect(mongoURI, config.database.mongo.server, function (err, client) {

server/utils/passport/local-login.js:3:import { MongoClient } from 'mongodb';
server/utils/passport/local-login.js:29:      MongoClient.connect(mongoURI, config.database.mongo.server, function (err, client) {

server/utils/passport/local-signup.js:3:import { MongoClient } from 'mongodb';
server/utils/passport/local-signup.js:25:    MongoClient.connect(mongoURI, config.database.mongo.server, function (err, client) {

server/app.js:11:import { MongoClient } from 'mongodb';
server/app.js:96:  return yield MongoClient.connect(mongoURI, config.database.mongo.server);
```

`client.close();` might be the culprit.

**Comment by tashrifbillah** [comment]
https://www.mongodb.com/community/forums/t/too-many-open-files-mongo-4-2/8585/12

https://www.npmjs.com/package/mongoose-updated-driver

**Comment by tashrifbillah** [comment]
`ulimit -a`:

```vim
[root@dpstage dpdash]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31116
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31116
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

We increased `1024`-->`64000` in `/etc/security/limits.conf`.

For the change to take effect, log out and log back into the shell.

**Comment by tashrifbillah** [comment]
```bash
[root@dpstage proc]# cd /proc
[root@dpstage proc]# 
while [ 1 ]
do
for pid in [0-9]*; do value=$(ls /proc/$pid/fd/ | wc -l); if [ $value -gt 100 ]; then echo PID $pid: $value file descriptors; fi; done
sleep 15
echo ''
done

PID 171: 106 file descriptors
PID 33320: 141 file descriptors
```
https://stackoverflow.com/questions/65097034/mongo-4-4-crashes-with-too-many-open-files

**Comment by tashrifbillah** [comment]
https://www.mongodb.com/docs/manual/reference/ulimit/

Another relevant post:
https://dba.stackexchange.com/questions/197328/mongo-crashing-due-to-too-many-open-files

**Comment by tashrifbillah** [comment]
This script should already set the `ulimit -n` and `ulimit -u`:
https://github.com/AMP-SCZ/dpdash/blob/pnl-devel/singularity/configure.sh
